### ISSUE TITLE
After upgrading to the latest kernel (5.6.15), dnf complains about repo mbp-fedora-kernel

### ISSUE THREAD

**Issue by folke** [mikeeq/mbp-fedora-kernel#13]
I'm getting the errors below when running `dnf update --refresh`
```
mbp-fedora-kernel                                                                       1.5 kB/s | 506  B     00:00    
Errors during downloading metadata for repository 'mbp-fedora-kernel':
  - Status code: 503 for http://fedora-mbp-repo.herokuapp.com/repodata/repomd.xml (IP: 52.213.218.43)
Error: Failed to download metadata for repo 'mbp-fedora-kernel': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

**Comment by mikeeq** [comment]
You can remove mbp-fedora-kernel yum repo from: 
`/etc/yum.repos.d/mbp-fedora-kernel.repo` as it shouldn't be used for kernel upgrades (please use update_kernel_mbp script instead). I had plans to integrate custom kernel modules into one `.rpm` package so kernel could be upgraded via `dnf upgrade` but never got a time to do it :(

I will remove it from feature release of mbp-fedora and add it back whenever it'll be fully working.

**Comment by folke** [comment]
I figured something like that 🙂

Thanks again for all the great work!!
