### ISSUE TITLE
wifi on MacBook Pro 15.4 (13" 2019)

### ISSUE THREAD

**Issue by yurnam** [mikeeq/mbp-fedora-kernel#2]
Great Project thanks! 
works pretty well except wifi on my 13 inch 2019 mbp
Maybe because it uses the BCM4377 and i can't find any information about linux support.
brcmfmac doesn't even attempt to load.

**Comment by yurnam** [comment]
output when i run:
ioreg | grep RequestedFiles

> "RequestedFiles" = ({"Firmware"="C-4377__s-B3/formosa.trx","TxCap"="C-4377__s-B3/formosa-X3.txcb","Regulatory"="C-4377__s-B3/formosa-X3.clmb","NVRAM"="C-4377__s-B3/P-formosa-X3_M-SPPR_V-u__m-3.1.txt"})

so i copied these files, renamed them according to the guide and put them into /lib/firmware/brcm.
then i tried adding into brcmfmac source files (just replaced the chip_id and hw_id in wifi.patch). 
After compiling brcmfmac sees the chip and loads the firmware, but no interface is created.
output of dmesg | grep brcmfmac:

[    4.721277] RIP: 0010:brcmf_fweh_detach+0x5b/0x60 [brcmfmac]
[    4.721293]  brcmf_detach+0x80/0xd0 [brcmfmac]
[    4.721300]  brcmf_pcie_remove+0x70/0x110 [brcmfmac]
[    4.721311]  brcmf_pcie_setup+0x38/0xd70 [brcmfmac]
[    4.721320]  brcmf_fw_request_done+0x65/0xe0 [brcmfmac]

i have no idea how to get the information needed for implementing a working solution.

**Comment by AdityaGarg8** [comment]
> Great Project thanks!
> works pretty well except wifi on my 13 inch 2019 mbp
> Maybe because it uses the BCM4377 and i can't find any information about linux support.
> brcmfmac doesn't even attempt to load.

Finally the support has arrived
