### ISSUE TITLE
Docs on how to build custom kernel based on this repo?

### ISSUE THREAD

**Issue by sxiii** [mikeeq/mbp-fedora-kernel#43]
Would it be possible to add documentation on how to use this repo against latest kernel release, like, for instance, 5.15.4 or 5.16-rc2? I would be happy to build newer releases and test them out, but that would be much easier if there would be a workflow docs for that matter.

Thanks

**Comment by MrMan314** [comment]
Bump

**Comment by mikeeq** [comment]
I added a small section in the README how to do it - let me know if you need more details ;)

<https://github.com/mikeeq/mbp-fedora-kernel#how-to-build-mbp-fedora-kernel>
