### ISSUE TITLE
Every time I try to update kernel it's locked to fc33 somewhy

### ISSUE THREAD

**Issue by sxiii** [mikeeq/mbp-fedora-kernel#45]
Every time I run kernel update it succeeds, but:
```
===]> Info: Current kernel version: 5.15.5-200.mbp.fc33.x86_64
===]> Info: Downloading latest mbp kernel: 5.15.5-f35
```

So it seems it's never actually updated (or is it?) to f35.

Might be a naming convention problem, but still:

```
[root@fedora-mbp ~]# uname -a
Linux fedora-mbp 5.15.5-200.mbp.fc33.x86_64 #1 SMP Wed Dec 1 09:46:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
Weird to see "f33" kernel on Fedora 35.

**Comment by Runaway1956** [comment]
I'm seeing precisely the same thing.  I've updated kernel exactly following directions 5 times, and on reboot, I'm seeing fc33 instead of fc35.  I'm using this command, copy/pasted from the instructions page:
KERNEL_VERSION="5.15.5-f35" UPDATE_SCRIPT_BRANCH="v5.15-f35" update_kernel_mbp

**Comment by mikeeq** [comment]
It's a version of the base image (fedora:33) used for building kernel packages. I can't use newer versions as they are based on newer versions of gcc and kernel is failing to build, that's the reason you see fc33 in the kernel name. Nothing to worry about. Kernel is built from f35 source. I was trying to change that part in the kernel name but it requires too many modifications in kernel.spec, not worth it ;)

**Comment by Runaway1956** [comment]
Thanks for the response!  That's one puzzling factor solved.
