### ISSUE TITLE
kernel 5.19.1 build and test OK; see 2022-08-14_Kernel_5.19_Test_Week

### ISSUE THREAD

**Issue by spital** [mikeeq/mbp-fedora-kernel#67]
Quick hack, working:
kernel 5.19.1 build and test OK; see 2022-08-14_Kernel_5.19_Test_Week
https://fedoraproject.org/wiki/Test_Day:2022-08-14_Kernel_5.19_Test_Week

src::
https://github.com/spital/mbp-fedora-kernel/tree/v5.19.1-f36-tst

**Comment by mikeeq** [comment]
Thanks for testing!
